#!/bin/bash

appName="$*"
echo="Installing $appName"

all="$ichrome $ivlc $izoom" 

ichrome="[[ $appName = "Chrome" || $appName = "chrome" ]]"
ivlc="[[ $appName = "VLC" || $appName = "vlc" ]]"
izoom="[[ $appName = "Zoom" || $appName = "zoom" ]]"

if $ichrome ; then

    #### Chrome ####

    cd ~/Downloads
    echo "Downloading Chrome"
    curl -O https://dl.google.com/chrome/mac/stable/CHFA/googlechrome.dmg
    open ~/Downloads/googlechrome.dmg
    set timeout 120

   # Suggestion from StackOverflow. Use a while loop and the brackets to verify the existing folder

    while ! [[ -d /Volumes/Google\ Chrome/ ]] ; do
	sleep 1
    done

    echo "Copying Chrome to /Applications. Please wait." &&
    cp -R /Volumes/Google\ Chrome/Google\ Chrome.app /Applications && open /Applications/Google\ Chrome.app
    diskutil eject Google\ Chrome

    defaults write com.apple.dock persistent-apps -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Google Chrome.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
    killall Dock

    Echo Chrome Installed
#    exit 0

elif $ivlc ; then

    #### VLC ####

    cd ~/Downloads

    echo "Downloading VLC Media Player"
    DVLC="curl -O https://mirror.clarkson.edu/videolan/vlc/3.0.3/macosx/vlc-3.0.3.dmg"

    if $DVLC ; then
        :
    else
        open https://www.videolan.org/vlc/download-macosx.html
        exit 1
    fi

    open ~/Downloads/vlc*

    while [[ ! -d /Volumes/VLC\ media\ player/ ]] ; do
	sleep 1
    done
	
    echo "Copying VLC to /Applications. Please wait"	
    cp -R /Volumes/VLC\ media\ player/VLC.app /Applications/ && diskutil eject /Volumes/VLC\ media\ player

# apparently you can use rsync --progress to copy the files over and show a
# progress bar, but it skips /Volumes/VLC\ media\ player
# would like to use that so I'll figure that out next time maybe

    open /Applications/VLC.app
    defaults write com.apple.dock persistent-apps -array-add "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/VLC.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>"
    echo VLC Installed
 #   exit 0

elif $izoom ; then

    #### Zoom ####

    cd ~/Downloads

    DZOOM="curl -O https://zoom.us/client/4.1.27695.0702/zoomusInstaller.pkg"

    if $DZOOM ; then
        :
    else
        open https://zoom.us/download
        exit 1
    fi

    open ~/Downloads/zoomusInstaller.pkg*

else
    echo This app is unavailable to install using this tool
    exit 0

fi
